apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: x4bcontainerregistry
  pass_credentials_all: false
  password: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlVWVzc6T1JDQjozVkNIOjY2UEI6R1kyWjpOU01KOldIVVE6Qjc3WDpLWTdaOlRaU1A6UkZZWDpIVTdRIn0.eyJqdGkiOiI5NGM5ZmJmNS1lZjBkLTQ0OWEtYWZhNi1jNWQzMGJkZTMxMTgiLCJzdWIiOiJtYXJjb3MuYWxtZWlkYUB4Y29tcG9uZW50LmNvbSIsIm5iZiI6MTY0MDYwMDg5OSwiZXhwIjoxNjQwNjA1Mzk5LCJpYXQiOjE2NDA2MDA4OTksImlzcyI6IkF6dXJlIENvbnRhaW5lciBSZWdpc3RyeSIsImF1ZCI6Ing0YmNvbnRhaW5lcnJlZ2lzdHJ5LmF6dXJlY3IuaW8iLCJ2ZXJzaW9uIjoiMS4wIiwicmlkIjoiZjVmYjEyNmY2YjZiNDcwNTkzMWM1OTZlMzY1OGQ0NmYiLCJhY2Nlc3MiOlt7IlR5cGUiOiJhcnRpZmFjdC1yZXBvc2l0b3J5IiwiTmFtZSI6InJlcG8iLCJBY3Rpb25zIjpbInB1bGwiXX1dLCJyb2xlcyI6W10sImdyYW50X3R5cGUiOiJhY2Nlc3NfdG9rZW4iLCJhcHBpZCI6IjA0YjA3Nzk1LThkZGItNDYxYS1iYmVlLTAyZjllMWJmN2I0NiJ9.eyyAmHKKWeDUDi4QgfZTXBnA_S4lGjsgalffAh4lgOCCHOcNMplnHZafd5OLSZKMutLrlq_NG7AQ5ftg_aCA03U8GTZYmAKnW5-ooevCgz_JLj1htoped_Mkk2rGvB17m0HG1aKl_PNMAdCdzPFopTpFGAItpRCSAGIk9U5zdK4YcyHP7TZ3putLBm2NNkOCmfQCR3S5EJHl6aAVmeKdsLAx9aMNcn7Pnm0FM0Jc2MqqNRRwf97Hw9p-M8GbeB-J6Z-RCbVtAqwO3p5bnO-_gUYq2J9SaXmOyY8iFVDA3BrzQF1sciw4ocxdqt3JXdo9Ns-vazyv4c84xAYoXovy6Q
  url: https://x4bcontainerregistry.azurecr.io/helm/v1/repo
  username: 00000000-0000-0000-0000-000000000000
