apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: x4bcontainerregistry
  pass_credentials_all: false
  password: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ikk3QjY6NlQ0QTpUWlYzOllJT046Rk9ESjpOWlRDOjVVUFk6M0JWMzpGRlhPOlE1NEs6M0JCSzpHVFgzIn0.eyJqdGkiOiI3MDQ4MmZjOS0yNzk2LTQyZGYtOWNhOS1kYjliZDYxMDc1OGIiLCJzdWIiOiJtYXJjb3MuYWxtZWlkYUB4Y29tcG9uZW50LmNvbSIsIm5iZiI6MTY0NzUyNjEzNCwiZXhwIjoxNjQ3NTMwNjM0LCJpYXQiOjE2NDc1MjYxMzQsImlzcyI6IkF6dXJlIENvbnRhaW5lciBSZWdpc3RyeSIsImF1ZCI6Ing0YmNvbnRhaW5lcnJlZ2lzdHJ5LmF6dXJlY3IuaW8iLCJ2ZXJzaW9uIjoiMS4wIiwicmlkIjoiZjVmYjEyNmY2YjZiNDcwNTkzMWM1OTZlMzY1OGQ0NmYiLCJhY2Nlc3MiOlt7IlR5cGUiOiJhcnRpZmFjdC1yZXBvc2l0b3J5IiwiTmFtZSI6InJlcG8iLCJBY3Rpb25zIjpbInB1bGwiXX1dLCJyb2xlcyI6W10sImdyYW50X3R5cGUiOiJhY2Nlc3NfdG9rZW4iLCJhcHBpZCI6IjA0YjA3Nzk1LThkZGItNDYxYS1iYmVlLTAyZjllMWJmN2I0NiJ9.OSjzzxA7tk3FpFPt29WtMPNSRxaTzovSVDn1EnnrsYnlPZ0EIHKn14eA0_1r1cHlod1_dBYTJ0KkID-opK4eJbewQOR_PX6wEmhZl6QX5vlVraTLiKRrd9u4WPKuvXTAnRmmz19IWeKa9JDW3_SBFs6lt6DOH2iXUcUFwC9I7srayfSVkexzO1DKd_VFbqGWMTE4opnmPt_TpMxlYgs-VFYF-FRgrBEs1broxBb4GlWJGOEK-MFulSTq-O9vZUOnEo_v5v4TK6v69DeUkNTBRO527lkIPaSCE6JqSL0vRnoHYQEHI-OVh5XdSHtOTEf8FfDZNEN-jzz5Cha4okLQ_w
  url: https://x4bcontainerregistry.azurecr.io/helm/v1/repo
  username: 00000000-0000-0000-0000-000000000000
